services:
  postgres:
    image: postgres:15-alpine
    container_name: restaurantos_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: santiago09
      POSTGRES_DB: restaurantos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:15-alpine
    container_name: restaurantos_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: santiago09
      POSTGRES_DB: restaurantos_test
    ports:
      - "5433:5432"

volumes:
  postgres_data:
